<?php
define('DEFAULT_PAD_LEFT_NUMBER', 7);
define('DEFAULT_PAGINATION_NUMBER', 8);
define('TERRAIN_CODE_PREFIXE', 'TER');
define('APPARTEMENT_CODE_PREFIXE', 'APP');
define('CONTRAT_CODE_PREFIXE', 'CON');
define('FACTURE_LOYER_CODE_PREFIXE', 'FAL');
define('FACTURE_VISITE_CODE_PREFIXE', 'FAV');
define('FACTURE_ACHAT_CODE_PREFIXE', 'FAA');
define('FACTURE_CAUTION_CODE_PREFIXE', 'FAC');
define('FACTURES_PREFIXES', [
    'loyer' => FACTURE_LOYER_CODE_PREFIXE,
    'visite' => FACTURE_VISITE_CODE_PREFIXE,
    'achat' => FACTURE_ACHAT_CODE_PREFIXE,
    'caution' => FACTURE_CAUTION_CODE_PREFIXE,
]);
