<?php
define('DEFAULT_PAD_LEFT_NUMBER', 7);
define('DEFAULT_PAGINATION_NUMBER', 8);
define('TERRAIN_CODE_PREFIXE', 'TER');
define('APPARTEMENT_CODE_PREFIXE', 'APP');
define('CONTRAT_CODE_PREFIXE', 'CON');
define('FACTURE_CODE_PREFIXE', 'FAC');
